[pytest]
markers =
    unit: tests that do not require external services
    integration: tests that require external services
    external: tests that depend on external services

addopts = -m "not external"